filebeat.inputs:
- type: log
  paths:
    - /var/log/cmd.log
  fields:
    fileset.module: system
    fileset.name: cmd
  fields_under_root: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
setup.kibana:
output.redis:
  hosts: ["172.16.2.113:6379"]
  password: "pass"
  key: "list_logs"
  db: 0
  timeout: 5

